### ISSUE TITLE
Cannot Uninstall

### ISSUE THREAD

**Issue by Pleasance13** [Jannomag/shortix#10]
There's no option to say no to installing the service in Update Shortix

**Comment by Jannomag** [comment]
I will add an uninstaller. For now you just can delete the service by using `systemctl --user disable shortix.service` and remove the file in `~/.config/systemd/user/shortix.service`.

I will either add a single line command to the readme or a script. It will take some time for it.

**Comment by Jannomag** [comment]
Uninstaller is now available.
I also double check if there's an option to say no for installing the service.
There's on both cases, install and update - at least for me. I always asks for the service and if selecting now it even removes it.
