### ISSUE TITLE
Incompatibility: Hyperdimension Neptunia Re;Birth series

### ISSUE THREAD

**Issue by RueGorE** [Jannomag/shortix#5]
Issue: Shortix tries to produce symlink folders for this series of games but they end up as "unknown file type" files. Thus, double-clicking the file(s) opens a "Choose Application - Dolphin" dialog.

Game Name: Hyperdimension Neptunia Re;Birth1
Steam Prefix ID: 282900
Resulting name of the created file: Hyperdimension Neptunia Re (Birth1;282900;) - 

Game Name: Hyperdimension Neptunia Re;Birth2 Sisters Generation
Steam Prefix ID: 351710
Resulting name of the created file: Hyperdimension Neptunia Re (Birth2 Sisters Generation;351710;) - 

Game Name: Hyperdimension Neptunia Re;Birth3 V Generation
Steam Prefix ID: 353270
Resulting name of the created file: Hyperdimension Neptunia Re (Birth3 V Generation;353270;) - 

Affects Compat Data and/or Shader Cache symlinks?: YES, BOTH

Additional notes: I'm using all options from the Shortix installation (yes to Steam ID prefix, yes to size). If I don't include the extra prefixes, the resulting file name becomes "Hyperdimension Neptunia Re" and is still of an unknown file type. My guess is Shortix is stumbling over the semicolon symbol in the game name, therefore this may affect other games with semicolons in their names as well.

**Comment by Jannomag** [comment]
I was just waiting for this.

I will try to modify the separator symbol, but there will be always some weird Japanese game with strange characters in the name making issues.

Or I just add code to remove the semicolon before doing the Shortix stuff. Give me some time!

**Comment by Jannomag** [comment]
It should work now, just update using the Shortix Updater on your desktop. 
Shortix will remove the semicolon from the name, it was the easiest solution to fix this issue.

**Comment by RueGorE** [comment]
Sometimes the simplest solutions are the best solutions -- awesome! Thank you!
